# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOhZ9iiHCHTn4vMeKWTIrtfG8_MM37Jc
"""

import streamlit as st

st.title("Mi primera aplicacion en Streamlit")
st.header("Este es un encabezado")
st.subheader("Este es un subencabezado")
st.write("Este es una introduccion a streamlit, donde exploraremos como construir aplicaciones interactivas")